Add config options for Default Claim Permissions.
WasabiThumb/xclaim pull request #160
Opened 2024-12-15 08:54 UTC by Paperboypaddy

This change adds some simple options in config for each kind of permission that can be changed. Allowing admins to set default values instead of using plugins hardcoded defaults. This being a very small change, no added commands, permissions, gui layouts, should be a simple way at first to allow admins to control some of these hardcoded options.

Issue #155

2024-12-15 17:02 UTC, WasabiThumb requested changes
Almost perfect! Thanks for taking the time to understand the config framework <3

2024-12-15 17:02 UTC, WasabiThumb commented on src/main/java/codes/wasabi/xclaim/api/enums/Permission.java
> +    BUILD("perm-build-name", "perm-build-description", TrustLevel.fromString(XClaim.mainConfig.permissions().defaultBuild()), BuildBreakHandler.Build.class),
Passing the TrustLevel through the constructor causes the level to be evaluated when the class loads, which is technically a different lifecycle stage from when the config loads. For instance, this would break if another plugin caused the TrustLevel class to initialize before XClaim fully loaded.

Having a global ``XClaim.mainConfig`` to begin with is dicey, and is removed in v2. The existence of v2 in general is the reason why I've held off on adding this feature.

I suggest that the constructor to be adapted to take ``Function<PermissionsConfig, String>`` in which case we can pass ``PermissionsConfig::defaultBuild``, ``PermissionsConfig::defaultBreak``, etc. This value can be stored to a field like ``computeDefaultTrust``, and then the method ``getDefaultTrust`` can do ``return this.computeDefaultTrust.apply(XClaim.mainConfig.permissions())``.

This defers the evaluation to the time when ``getDefaultTrust`` is called; as long as the method is called at a valid time, it will produce a valid result. The class being loaded early would no longer corrupt the stored values for its entire lifetime.

2024-12-15 23:59 UTC, Paperboypaddy commented on src/main/resources/config.toml
> +default-delete = "NONE
Will be fixed in next commit.

2024-12-15 23:59 UTC, Paperboypaddy commented on src/main/resources/config.toml
> +#DEFAULT: TRUSTED
Will be fixed in next commit.

2024-12-16 00:00 UTC, Paperboypaddy commented on src/main/resources/config.toml
> +default-build = "TRUSTED"
Yea, my only worry there. I've made that change and renamed everything to match this.

2024-12-16 00:00 UTC, Paperboypaddy commented on src/main/java/codes/wasabi/xclaim/config/impl/defaulting/sub/DefaultingPermissionsConfig.java
> +        return this.nullFallback(this.backing().defaultBuild(),"TRUSTED");
Whoops. I cant even tell there wasn't a space there in Intellij.

2024-12-16 00:00 UTC, Paperboypaddy commented on src/main/java/codes/wasabi/xclaim/api/enums/TrustLevel.java
> +    public static TrustLevel fromString(String raw) {
Fixed.

2024-12-16 00:03 UTC, Paperboypaddy commented on src/main/java/codes/wasabi/xclaim/api/enums/Permission.java
> +    BUILD("perm-build-name", "perm-build-description", TrustLevel.fromString(XClaim.mainConfig.permissions().defaultBuild()), BuildBreakHandler.Build.class),
This is the only thing I'm having troubles thinking on where to put a new class or methods for this. Completely understand how to implement such thing. Doing the right way on the other hand is a tad tricky. I'll work on getting something working in the meantime if you don't respond right away.

2024-12-16 02:06 UTC, Paperboypaddy commented
> Almost perfect! Thanks for taking the time to understand the config framework <3

No problem at all!! At first it confused me but once I figured out what it was doing it made sense how to add options to the config. Actually it was really easy to add stuff, maybe not as easy as yaml but still decently easy to grasp. 


> I suggest that the constructor be adapted to take `Function<PermissionsConfig, String>` in which case we can pass `PermissionsConfig::defaultBuild`, `PermissionsConfig::defaultBreak`, etc. This value can be stored to a field like `computeDefaultTrust`, and then the method `getDefaultTrust` can do `return this.computeDefaultTrust.apply(XClaim.mainConfig.permissions())`.
> 
> This defers the evaluation to the time when `getDefaultTrust` is called; as long as the method is called at a valid time, it will produce a valid result. The class being loaded early would no longer corrupt the stored values for its entire lifetime.

Implemented this in almost exactly how you described I think. Had a couple of issue's at first but came down to forgetting to change the table name in TomlRootConfig LOL. Everything seems to work as expected. I do find it a bit strange that a new claim doesn't set the permissions in the claims.yml, but actually makes it really useful to have these defaults set in the config instead.

I did run a test what would happen if a value wasn't set in the config, and as designed a unset value in config fallback to NONE. As shown on the first Build permission:
<img width="264" alt="image" src="https://github.com/user-attachments/assets/e3ed582a-3c75-4a12-ba1d-baf2150a59d2" />

Let me know if I missed any important Annotations, I probably did somewhere.

2024-12-16 02:38 UTC, WasabiThumb approved these changes
lgtm :)

2024-12-16 02:45 UTC, merged